FROM rust:1.88-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install cargo-watch

WORKDIR /app

EXPOSE 8000

CMD ["cargo", "watch", "-x", "run"]
